version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb-chalender
    ports:
      - 27500:27017
    volumes:
      - data:/chalender-mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
volumes:
  data: {}

networks:
  default:
    name: mongodb_network